import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Antarktika',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="navigation">
          <Link className="navigation-logo"  href="/">
            <img className='logo' src="/twitter-removebg-preview.png" alt="" />
          </Link>
<div>


          <Link className="navigation-link" href="/about">
            ABOUT
          </Link>
          <Link className="navigation-link" href="/contact">
            CONTACT
          </Link>
</div>
        </nav>
        <main className="main-container">{children}</main>
        <footer>Created by Nikola Ivanov</footer>
      </body>
    </html>
  );
}
